export const Data = [
  {
    "id": 1,
    "name": "Gaming Joy Stick",
    "code": "PRD001",
    "category": "Electronics",
    "brand": "Brand Name",
    "price": 99.99,
    "unit": "pcs",
    "quantity": 150,
    "image": "/imgs/product-1.png",
  },
  {
    "id": 2,
    "name": "Wireless Earphones",
    "code": "PRD002",
    "category": "Electronics",
    "brand": "Tech Pro",
    "price": 89.99,
    "unit": "pcs",
    "quantity": 320,
    "image":"/imgs/product-2.png",
  },
  {
    "id": 3,
    "name": "Smart Watch Pro",
    "code": "PRD003",
    "category": "Electronics",
    "brand": "Tech Pro",
    "price": 98.00,
    "unit": "pcs",
    "quantity": 200,
    "image": "/imgs/product-3.png",
  },
  {
    "id": 4,
    "name": "USB-C Fast Charger",
    "code": "PRD004",
    "category": "Electronics",
    "brand": "Tech Pro",
    "price": 86.00,
    "unit": "pcs",
    "quantity": 80,
    "image": "/imgs/product-4.png",
  },
  {
    "id": 5,
    "name": "Portable Bluetooth Speaker",
    "code": "PRD005",
    "category": "Electronics",
    "brand": "Tech Pro",
    "price": 32.00,
    "unit": "pcs",
    "quantity": 110,
    "image": "/imgs/product-5.png",
  },
  {
    "id": 6,
    "name": "Magic Keyboard",
    "code": "PRD006",
    "category": "Electronics",
    "brand": "Tech Pro",
    "price": 49.00,
    "unit": "pcs",
    "quantity": 10,
    "image":"/imgs/product-6.png",
  },
  {
    "id": 7,
    "name": "MacBook Pro 16\"",
    "code": "PRD007",
    "category": "Electronics",
    "brand": "Tech Pro",
    "price": 99.00,
    "unit": "pcs",
    "quantity": 10,
    "image":"/imgs/product-7.png",
  },
  {
    "id": 8,
    "name": "Wireless Headphones",
    "code": "PRD008",
    "category": "Electronics",
    "brand": "Tech Pro",
    "price": 109.00,
    "unit": "pcs",
    "quantity": 200,
    "image": "/imgs/product-8.png",
  }
]